name: Feature request
description: Suggest an improvement
labels: [enhancement, triage]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Why / use case
